const PipelineEvents = {
  QUERY_RECEIVED: "QUERY_RECEIVED",

  EMBEDDING_STARTED: "EMBEDDING_STARTED",
  EMBEDDING_DONE: "EMBEDDING_DONE",

  RETRIEVAL_STARTED: "RETRIEVAL_STARTED",
  RETRIEVAL_DONE: "RETRIEVAL_DONE",

  CONTEXT_BUILT: "CONTEXT_BUILT",

  PROMPT_CREATED: "PROMPT_CREATED",

  LLM_STARTED: "LLM_STARTED",
  LLM_DONE: "LLM_DONE",

  PIPELINE_COMPLETE: "PIPELINE_COMPLETE"
};

export default PipelineEvents;